# Generated by Django 3.0.3 on 2020-02-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('meta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MarkedObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.IntegerField()),
                ('obj_type', models.CharField(max_length=10)),
                ('obj_lat', models.FloatField()),
                ('obj_lon', models.FloatField()),
                ('obj_meta', models.TextField(blank=True, null=True)),
                ('other_id', models.IntegerField()),
                ('other_lat', models.FloatField()),
                ('other_lon', models.FloatField()),
                ('other_meta', models.TextField(blank=True, null=True)),
                ('mark', models.IntegerField()),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Iteration')),
            ],
        ),
    ]
